modLoader="javafml"
loaderVersion="[2,]"
license="MIT"

[[mods]]
modId="buildcraftbuilders"
version="1.21.11-8.0.0"
displayName="BuildCraft Builders"
description='''
The builders module for BuildCraft 8.
'''
[[dependencies.buildcraftbuilders]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.buildcraftbuilders]]
    modId="buildcraftapi"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"

[[dependencies.buildcraftbuilders]]
    modId="buildcraftlib"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"

[[dependencies.buildcraftbuilders]]
    modId="buildcraftcore"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"
