modLoader="javafml"
loaderVersion="[2,]"
license="MIT"

[[mods]]
modId="buildcraftfactory"
version="1.21.10-8.0.0"
displayName="BuildCraft Factory"
description='''
The factory module for BuildCraft 8. (Stub)
'''
[[dependencies.buildcraftfactory]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.buildcraftfactory]]
    modId="buildcraftcore"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"
