modLoader="javafml"
loaderVersion="[2,]"
license="MIT"

[[mods]]
modId="buildcrafttransport"
version="1.21.11-8.0.0"
displayName="BuildCraft Transport"
description='''
The transport module for BuildCraft 8. (Stub)
'''
[[dependencies.buildcrafttransport]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.buildcrafttransport]]
    modId="buildcraftcore"
    type="required"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"
