modLoader="javafml"
loaderVersion="[2,]"
license="MIT"

[[mods]]
modId="buildcraftlib"
version="1.21.11-8.0.0"
displayName="BuildCraft Library"
description='''
The library module for BuildCraft 8.
'''
[[dependencies.buildcraftlib]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"
