modLoader="javafml"
loaderVersion="[2,]"
license="MIT"

[[mods]]
modId="buildcraftrobotics"
version="1.21.11-8.0.0"
displayName="BuildCraft Robotics"
description='''
The robotics module for BuildCraft 8. (Stub)
'''
[[dependencies.buildcraftrobotics]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.buildcraftrobotics]]
    modId="buildcraftcore"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"

[[dependencies.buildcraftrobotics]]
    modId="buildcraftfactory"
    type="optional"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"
