modLoader="javafml"
loaderVersion="[2,]"
license="MIT"

[[mods]]
modId="buildcraftenergy"
version="1.21.11-8.0.0"
displayName="BuildCraft Energy"
description='''
The energy module for BuildCraft 8. (Stub)
'''
[[dependencies.buildcraftenergy]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.buildcraftenergy]]
    modId="buildcraftcore"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"
