package buildcraft.energy.client;

import net.minecraft.resources.Identifier;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.neoforge.client.extensions.common.IClientFluidTypeExtensions;
import net.neoforged.neoforge.client.extensions.common.RegisterClientExtensionsEvent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import buildcraft.energy.BCEnergyFluids;

/**
 * Client-side fluid rendering extensions for all BuildCraft energy fluids.
 * Registered manually on the mod event bus from BCEnergy.
 *
 * Uses pre-recolored static PNG textures generated by the build-time texture
 * script (replicating the 1.12.2 AtlasSpriteFluid per-pixel lerp formula).
 * Colors are baked into the sprites, so no runtime tint is needed.
 */
public class BCEnergyFluidsClient {

    private static final Logger LOGGER = LoggerFactory.getLogger(BCEnergyFluidsClient.class);

    /**
     * Register IClientFluidTypeExtensions for every BC energy fluid so that
     * DynamicFluidContainerModel (used by buckets and fluid shards) can find
     * the correct still/flow textures and tint color.
     */
    @SubscribeEvent
    public static void onRegisterClientExtensions(RegisterClientExtensionsEvent event) {
        LOGGER.info("[BCEnergyFluidsClient] Registering IClientFluidTypeExtensions for {} fluid entries.", BCEnergyFluids.ALL.size());
        for (BCEnergyFluids.FluidEntry entry : BCEnergyFluids.ALL) {
            String spriteName = entry.baseName() + "_heat_" + entry.heat();
            final Identifier stillId = Identifier.fromNamespaceAndPath("buildcraftunofficial", "block/fluids/" + spriteName + "_still");
            final Identifier flowId = Identifier.fromNamespaceAndPath("buildcraftunofficial", "block/fluids/" + spriteName + "_flow");

            event.registerFluidType(new IClientFluidTypeExtensions() {
                public Identifier getStillTexture() {
                    return stillId;
                }

                public Identifier getFlowingTexture() {
                    return flowId;
                }

                public int getTintColor() {
                    // No tint — colors are baked into the pre-recolored sprites
                    return 0xFFFFFFFF;
                }

                @Override
                //? if >=26.1 {
                public void modifyFogColor(net.minecraft.client.Camera camera, float partialTick, net.minecraft.client.multiplayer.ClientLevel level, int renderDistance, float darkenWorldAmount, org.joml.Vector4f fluidFogColor) {
                //?} else {
                /*public org.joml.Vector4f modifyFogColor(net.minecraft.client.Camera camera, float partialTick, net.minecraft.client.multiplayer.ClientLevel level, int renderDistance, float darkenWorldAmount, org.joml.Vector4f fluidFogColor) {*/
                //?}
                    int color = entry.tintColor();
                    float r = ((color >> 16) & 0xFF) / 255.0F;
                    float g = ((color >> 8) & 0xFF) / 255.0F;
                    float b = (color & 0xFF) / 255.0F;
                    //? if >=26.1 {
                    fluidFogColor.set(r, g, b, 1.0F);
                    //?} else {
                    /*return fluidFogColor.set(r, g, b, 1.0F);*/
                    //?}
                }

                @Override
                public void modifyFogRender(net.minecraft.client.Camera camera, net.minecraft.client.renderer.fog.environment.FogEnvironment environment, float renderDistance, float partialTick, net.minecraft.client.renderer.fog.FogData fogData) {
                    float distance = entry.gaseous() ? 5.0F : 3.0F;
                    fogData.environmentalStart = 0.0F;
                    fogData.environmentalEnd = distance;
                    fogData.renderDistanceStart = 0.0F;
                    fogData.renderDistanceEnd = distance;
                }
            }, entry.fluidType().get());
        }
    }

    // 1.21.11 TODO: RegisterFluidModelsEvent is 26.1-only. On 1.21.11 fluids render from the
    // IClientFluidTypeExtensions still/flow textures registered above — no separate model reg.
    //? if >=26.1 {
    @SubscribeEvent
    public static void onRegisterFluidModels(net.neoforged.neoforge.client.event.RegisterFluidModelsEvent event) {
        LOGGER.info("[BCEnergyFluidsClient] RegisterFluidModelsEvent fired! Registering {} fluid entries.", BCEnergyFluids.ALL.size());
        for (BCEnergyFluids.FluidEntry entry : BCEnergyFluids.ALL) {
            // Reference the pre-recolored sprites:
            // "buildcraftunofficial:block/fluids/<baseName>_heat_<heat>_still"
            String spriteName = entry.baseName() + "_heat_" + entry.heat();
            Identifier stillId = Identifier.fromNamespaceAndPath("buildcraftunofficial", "block/fluids/" + spriteName + "_still");
            Identifier flowId = Identifier.fromNamespaceAndPath("buildcraftunofficial", "block/fluids/" + spriteName + "_flow");

            net.minecraft.client.resources.model.sprite.Material stillMat =
                new net.minecraft.client.resources.model.sprite.Material(stillId);
            net.minecraft.client.resources.model.sprite.Material flowMat =
                new net.minecraft.client.resources.model.sprite.Material(flowId);

            // No tint needed — colors are baked into the recolored sprites
            LOGGER.info("[BCEnergyFluidsClient] Registering fluid model for: {} (still={}, flow={})",
                entry.name(), stillId, flowId);
            event.register(
                new net.minecraft.client.renderer.block.FluidModel.Unbaked(stillMat, flowMat, null, null),
                entry.source().get(), entry.flowing().get()
            );
        }
        LOGGER.info("[BCEnergyFluidsClient] All fluid models registered successfully.");
    }
    //?}
}
