package buildcraft.energy.client;

import net.minecraft.resources.Identifier;
import net.neoforged.bus.api.SubscribeEvent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import buildcraft.energy.BCEnergyFluids;

/**
 * Client-side fluid rendering extensions for all BuildCraft energy fluids.
 * Registered manually on the mod event bus from BCEnergy.
 *
 * Uses pre-recolored static PNG textures generated by the build-time texture
 * script (replicating the 1.12.2 AtlasSpriteFluid per-pixel lerp formula).
 * Colors are baked into the sprites, so no runtime tint is needed.
 */
public class BCEnergyFluidsClient {

    private static final Logger LOGGER = LoggerFactory.getLogger(BCEnergyFluidsClient.class);

    @SubscribeEvent
    public static void onRegisterFluidModels(net.neoforged.neoforge.client.event.RegisterFluidModelsEvent event) {
        LOGGER.info("[BCEnergyFluidsClient] RegisterFluidModelsEvent fired! Registering {} fluid entries.", BCEnergyFluids.ALL.size());
        for (BCEnergyFluids.FluidEntry entry : BCEnergyFluids.ALL) {
            // Reference the pre-recolored sprites:
            // "buildcraftenergy:block/fluids/<baseName>_heat_<heat>_still"
            String spriteName = entry.baseName() + "_heat_" + entry.heat();
            Identifier stillId = Identifier.fromNamespaceAndPath("buildcraftenergy", "block/fluids/" + spriteName + "_still");
            Identifier flowId = Identifier.fromNamespaceAndPath("buildcraftenergy", "block/fluids/" + spriteName + "_flow");

            net.minecraft.client.resources.model.sprite.Material stillMat =
                new net.minecraft.client.resources.model.sprite.Material(stillId);
            net.minecraft.client.resources.model.sprite.Material flowMat =
                new net.minecraft.client.resources.model.sprite.Material(flowId);

            // No tint needed — colors are baked into the recolored sprites
            LOGGER.info("[BCEnergyFluidsClient] Registering fluid model for: {} (still={}, flow={})",
                entry.name(), stillId, flowId);
            event.register(
                new net.minecraft.client.renderer.block.FluidModel.Unbaked(stillMat, flowMat, null, null),
                entry.source().get(), entry.flowing().get()
            );
        }
        LOGGER.info("[BCEnergyFluidsClient] All fluid models registered successfully.");
    }
}
