package buildcraft.energy.client;

import net.minecraft.resources.Identifier;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.neoforge.client.extensions.common.IClientFluidTypeExtensions;
import net.neoforged.neoforge.client.extensions.common.RegisterClientExtensionsEvent;

import buildcraft.energy.BCEnergy;
import buildcraft.energy.BCEnergyFluids;

/**
 * Client-side fluid rendering extensions for all BuildCraft energy fluids.
 * Registered manually on the mod event bus from BCEnergy.
 *
 * Uses pre-rendered textures generated from the 1.12 AtlasSpriteFluid recoloring
 * formula. White tint since textures are already recolored.
 *
 * Textures are generated by scripts/generate_fluid_textures.py using the exact
 * 1.12 formula: result = (dark * (256 - data) + light * data) / 256
 */
public class BCEnergyFluidsClient {

    @SubscribeEvent
    public static void onRegisterClientExtensions(RegisterClientExtensionsEvent event) {
        for (BCEnergyFluids.FluidEntry entry : BCEnergyFluids.ALL) {
            final String name = entry.name();
            final Identifier still = Identifier.fromNamespaceAndPath(
                    BCEnergy.MODID, "block/fluid/" + name + "_still");
            final Identifier flow = Identifier.fromNamespaceAndPath(
                    BCEnergy.MODID, "block/fluid/" + name + "_flow");

            event.registerFluidType(new IClientFluidTypeExtensions() {
                @Override
                public Identifier getStillTexture() {
                    return still;
                }

                @Override
                public Identifier getFlowingTexture() {
                    return flow;
                }

                @Override
                public int getTintColor() {
                    // White — textures are pre-recolored with 1.12 formula
                    return 0xFFFFFFFF;
                }
            }, entry.fluidType().get());
        }
    }
}
