modLoader="javafml"
loaderVersion="[2,]"
license="MIT"

[[mods]]
modId="buildcraftcore"
version="1.21.11-8.0.0"
displayName="BuildCraft Core"
logoFile="logo.png"
credits="Created by SpaceToad"
authors="SpaceToad, BuildCraft Team"
description='''
Extending Minecraft with pipes, auto-crafting, quarries, engines and much more!
'''
[[dependencies.buildcraftcore]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.buildcraftcore]]
    modId="buildcraftapi"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"

[[dependencies.buildcraftcore]]
    modId="buildcraftlib"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"
